spring:
  datasource:
    # ??? 3306 ??????portfolio_db ?????????
    url: jdbc:mysql://localhost:3306/portfolio_db?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456  # ?? ??????? MySQL ???
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # ???????
    show-sql: true     # ?????? SQL ???????